---
- name: Ansible Playbook Zabbix init
  hosts: DEV
  become: true

  tasks:
    - name: apt update
      apt:
        update_cache: true

    - name: Copy docker files to remote
      copy:
        src: /home/dark/workspace/DCMonitoring/docker
        dest: /home/dark/
        owner: dark
        group: docker
        mode: "0755"

    # - name: Instal Zabbix server/frontend/agent
    #   get_url:
    #     url: https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb
    #     dest: /home/dark/
    #     owner: "dark"
    #     group: "docker"
    #     mode: "0750"
