version: '3.7'

services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
    depends_on:
      - mysql
    ports:
      - "10051:10051"

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: password
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "UTC"
    depends_on:
      - mysql
      - zabbix-server
    ports:
      - "80:8080"
    volumes:
      - nginx-conf:/etc/nginx/conf.d

volumes:
  mysql-data:
  nginx-conf:
